"""Phase C – v2 schema (attempts, progress, stats, reviews, cached_audio)

Revision ID: 13479edb7ec9
Revises: 696a63587a46
Create Date: 2025-11-18 13:51:30.705626

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13479edb7ec9"
down_revision: Union[str, Sequence[str], None] = "696a63587a46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_audio",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audio_ref", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cached_audio_audio_ref"), "cached_audio", ["audio_ref"], unique=False
    )
    op.create_index(
        op.f("ix_cached_audio_hash"), "cached_audio", ["hash"], unique=False
    )
    op.create_table(
        "daily_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("phrase_id", sa.String(), nullable=False),
        sa.Column("next_review", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=True),
        sa.Column("easiness", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_reviews_phrase_id"), "daily_reviews", ["phrase_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_reviews_user_id"), "daily_reviews", ["user_id"], unique=False
    )
    op.create_table(
        "phrase_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("phrase_id", sa.String(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("phonetic_distance", sa.Float(), nullable=False),
        sa.Column("semantic_accuracy", sa.Float(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("audio_ref", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phrase_attempts_created_at"),
        "phrase_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phrase_attempts_phrase_id"),
        "phrase_attempts",
        ["phrase_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phrase_attempts_user_id"), "phrase_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "user_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.String(), nullable=False),
        sa.Column("current_index", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("cefr_level", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_progress_lesson_id"), "user_progress", ["lesson_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_progress_updated_at"),
        "user_progress",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_progress_user_id"), "user_progress", ["user_id"], unique=False
    )
    op.create_table(
        "user_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=True),
        sa.Column("streak", sa.Integer(), nullable=True),
        sa.Column("total_attempts", sa.Integer(), nullable=True),
        sa.Column("total_passed", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_user_progress_user_id"), table_name="user_progress")
    op.drop_index(op.f("ix_user_progress_updated_at"), table_name="user_progress")
    op.drop_index(op.f("ix_user_progress_lesson_id"), table_name="user_progress")
    op.drop_table("user_progress")
    op.drop_index(op.f("ix_phrase_attempts_user_id"), table_name="phrase_attempts")
    op.drop_index(op.f("ix_phrase_attempts_phrase_id"), table_name="phrase_attempts")
    op.drop_index(op.f("ix_phrase_attempts_created_at"), table_name="phrase_attempts")
    op.drop_table("phrase_attempts")
    op.drop_index(op.f("ix_daily_reviews_user_id"), table_name="daily_reviews")
    op.drop_index(op.f("ix_daily_reviews_phrase_id"), table_name="daily_reviews")
    op.drop_table("daily_reviews")
    op.drop_index(op.f("ix_cached_audio_hash"), table_name="cached_audio")
    op.drop_index(op.f("ix_cached_audio_audio_ref"), table_name="cached_audio")
    op.drop_table("cached_audio")
    # ### end Alembic commands ###
