"""Initial schema

Revision ID: 4f121af30096
Revises: 
Create Date: 2025-11-07 21:02:28.390152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f121af30096'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lessons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('cefr_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lessons_level', 'Lessons', ['level'], unique=False)
    op.create_table('Meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_template', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_name', 'Users', ['name'], unique=False)
    op.create_table('LessonProgress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_dialogue_id', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson')
    )
    op.create_index('idx_lesson_progress_lesson', 'LessonProgress', ['lesson_id'], unique=False)
    op.create_index('idx_lesson_progress_status', 'LessonProgress', ['status'], unique=False)
    op.create_index('idx_lesson_progress_user', 'LessonProgress', ['user_id'], unique=False)
    op.create_table('Phrases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('grammar', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['Lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phrases_lesson', 'Phrases', ['lesson_id'], unique=False)
    op.create_table('Settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_key')
    )
    op.create_index('idx_settings_user', 'Settings', ['user_id'], unique=False)
    op.create_table('Attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('phoneme_diffs', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['Phrases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempts_created', 'Attempts', ['created_at'], unique=False)
    op.create_index('idx_attempts_phrase', 'Attempts', ['phrase_id'], unique=False)
    op.create_index('idx_attempts_user', 'Attempts', ['user_id'], unique=False)
    op.create_table('SRSMemory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.String(), nullable=False),
    sa.Column('strength_level', sa.Integer(), nullable=True),
    sa.Column('efactor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phrase_id'], ['Phrases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phrase_id', name='uq_user_phrase')
    )
    op.create_index('idx_srs_next_review', 'SRSMemory', ['next_review'], unique=False)
    op.create_index('idx_srs_phrase', 'SRSMemory', ['phrase_id'], unique=False)
    op.create_index('idx_srs_user', 'SRSMemory', ['user_id'], unique=False)
    # ### end Alembic commands ###
    
    # Initialize Meta table with db_version
    op.execute("INSERT INTO Meta (key, value) VALUES ('db_version', '1.0')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_srs_user', table_name='SRSMemory')
    op.drop_index('idx_srs_phrase', table_name='SRSMemory')
    op.drop_index('idx_srs_next_review', table_name='SRSMemory')
    op.drop_table('SRSMemory')
    op.drop_index('idx_attempts_user', table_name='Attempts')
    op.drop_index('idx_attempts_phrase', table_name='Attempts')
    op.drop_index('idx_attempts_created', table_name='Attempts')
    op.drop_table('Attempts')
    op.drop_index('idx_settings_user', table_name='Settings')
    op.drop_table('Settings')
    op.drop_index('idx_phrases_lesson', table_name='Phrases')
    op.drop_table('Phrases')
    op.drop_index('idx_lesson_progress_user', table_name='LessonProgress')
    op.drop_index('idx_lesson_progress_status', table_name='LessonProgress')
    op.drop_index('idx_lesson_progress_lesson', table_name='LessonProgress')
    op.drop_table('LessonProgress')
    op.drop_index('idx_users_name', table_name='Users')
    op.drop_table('Users')
    op.drop_table('Meta')
    op.drop_index('idx_lessons_level', table_name='Lessons')
    op.drop_table('Lessons')
    # ### end Alembic commands ###
